# Generated by Django 4.1.3 on 2022-11-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Price', models.IntegerField()),
                ('Model', models.DateField()),
                ('Chassis', models.CharField(max_length=30)),
            ],
        ),
    ]
